### ISSUE TITLE
disjonction in facets

### ISSUE THREAD

**Issue by lolostar** [metreeca/self#1]
Hi,

It would be nice if we could add more than one value in the facet value selector e.g. for a facet 
 'Country' we could have 'France' OR 'Italy' .

**Comment by knoan** [comment]
The query engine already supports disjunctive facets, but we need to finalise the UI: back to you as soon as we have an estimate.

**Comment by knoan** [comment]
Disjunctive facets will land in v0.49.0, slated for release early next week.

**Comment by lolostar** [comment]
Great 

Envoyé du LoloPhone

**Comment by knoan** [comment]
v0.49.0 with support for disjunctive facets available on maven central and https://demo.metreeca.com/

**Comment by cldwalker** [comment]
Was about to log a request for this. Thanks!
