### ISSUE TITLE
Disjunctive facet scenario results in 400

### ISSUE THREAD

**Issue by cldwalker** [metreeca/self#2]
**Environment**

- metreeca/self: 0.49.0
- web browser: Chrome 73.0
- operating system: Osx 10.11.4

**Description**

I wanted to use the disjunctive facets that landed with #1 to see things from multiple collections in one view

**How To Reproduce**

-  Load the [demo endpoint with demo data](https://demo.metreeca.com/apps/self/#endpoint=https://demo.metreeca.com/sparql)
- Add a < type field to see individual things from a collection: Click on + column. To the left of Collection, click on type field and click check mark to save
- Switch to Table view to see individual things by Collection
- Drag the Collection field to the facet/query right sidebar to create a Collection facet
- Check the Customer checkbox in the Collection facet and get an error message:
`SPARQL Protocol Error
The SPARQL endpoint
didn't accept the
request and says:
400 / .`

**Expected behaviour**

I expected the view to filter down to just Customer things

**Actual behaviour**

I received a 400 error message and was unable to filter

**Workarounds**

None found as I'm unable to filter

**Notes**

Additional info from the request that failed:

- Response:
```
{
    "error": "query-malformed",
    "cause": "BIND clause alias '0' was previously used"
}
```
- Query:
```
# tuples @ https://demo.metreeca.com/sparql

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

select

    ?0 ?0_label
    ?1 ?1_label

where {

    { select distinct ?0 ?1 where {

        { select distinct ?0 where {

            ?2 <http://rdfs.org/ns/void#rootResource> ?0 .

        } limit 100000 }

        optional {

            ?1 a <https://demo.metreeca.com/terms#Customer> .

        }

        bind ( <https://demo.metreeca.com/terms#Customer> as ?0)

    } limit 100000 }

    bind (coalesce(?0, false) as ?0_)

    optional { ?0_ rdfs:label ?0_label_0 filter (lang(?0_label_0) = '') }
    optional { ?0_ rdfs:label ?0_label_1 filter (lang(?0_label_1) = 'en') }

    bind (coalesce(?0_label_0, ?0_label_1) as ?0_label)

    bind (coalesce(?1, false) as ?1_)

    optional { ?1_ rdfs:label ?1_label_0 filter (lang(?1_label_0) = '') }
    optional { ?1_ rdfs:label ?1_label_1 filter (lang(?1_label_1) = 'en') }

    bind (coalesce(?1_label_0, ?1_label_1) as ?1_label)

}

order by

    asc(str(ucase(?0_label))) asc(?0)
    asc(str(ucase(?1_label))) asc(?1)

limit 1000
```

As an aside, thanks for this handy tool and open sourcing it! I've been using this via dydra to look at my sparql data.
Cheers, Gabriel

**Comment by knoan** [comment]
The issue affects only `Collection` facets with a single selected item; we'll have a look into the matter as soon as possible. In the meantime consider one of the following workarounds:

1. If you are trying to visualise the members of a single collection, just click on the collection icon, as shown in the tutorial;

2. If you are actually trying to visualise the members of multiple collections, drag the `Collection` field to the right of the `<type` field (so that it's not the first column), dismiss the error raised after selecting the first item a proceed to select the other required items.

![Screenshot 2019-04-20 at 16 27 45](https://user-images.githubusercontent.com/6105462/56458634-7ff5df00-6389-11e9-938d-8f57aed95571.png)

**Comment by cldwalker** [comment]
Thanks for the workaround! Silly that I didn't think of that.
Fyi, I did find that the current bug does effect one ore more checked Collections. I checked Office and Product Line this time and got the following 400:
```
{
    "error": "query-malformed",
    "cause": "Encountered \" \"^\" \"^ \"\" at line 17, column 13.\nWas expecting one of:\n    \"}\" ...\n    \"true\" ...\n    \"false\" ...\n    \"UNDEF\" ...\n    <Q_IRI_REF> ...\n    <PNAME_NS> ...\n    <PNAME_LN> ...\n    <INTEGER> ...\n    <INTEGER_POSITIVE> ...\n    <INTEGER_NEGATIVE> ...\n    <DECIMAL> ...\n    <DECIMAL_POSITIVE> ...\n    <DECIMAL_NEGATIVE> ...\n    <DOUBLE> ...\n    <DOUBLE_POSITIVE> ...\n    <DOUBLE_NEGATIVE> ...\n    <STRING_LITERAL1> ...\n    <STRING_LITERAL2> ...\n    <STRING_LITERAL_LONG1> ...\n    <STRING_LITERAL_LONG2> ...\n    "
}
```

<details><summary>Query for this 400</summary>

```
# tuples @ https://demo.metreeca.com/sparql

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

select

    ?0 ?0_label
    ?1 ?1_label

where {

    { select distinct ?0 ?1 where {

        values ?0 {
            ^<https://demo.metreeca.com/terms#Office>
            ^<https://demo.metreeca.com/terms#ProductLine>
        }

        { select distinct ?0 where {

            ?2 <http://rdfs.org/ns/void#rootResource> ?0 .

        } limit 100000 }

        optional {

            ?1 a ?0 .

        }

    } limit 100000 }

    bind (coalesce(?0, false) as ?0_)

    optional { ?0_ rdfs:label ?0_label_0 filter (lang(?0_label_0) = '') }
    optional { ?0_ rdfs:label ?0_label_1 filter (lang(?0_label_1) = 'en') }

    bind (coalesce(?0_label_0, ?0_label_1) as ?0_label)

    bind (coalesce(?1, false) as ?1_)

    optional { ?1_ rdfs:label ?1_label_0 filter (lang(?1_label_0) = '') }
    optional { ?1_ rdfs:label ?1_label_1 filter (lang(?1_label_1) = 'en') }

    bind (coalesce(?1_label_0, ?1_label_1) as ?1_label)

}

order by

    asc(str(ucase(?0_label))) asc(?0)
    asc(str(ucase(?1_label))) asc(?1)

limit 1000
```
</details>

The workaround is sufficient for me so there is no rush on my end for a bug fix

**Comment by knoan** [comment]
Fix available on `develop` branch: will land in the next (as yet unscheduled) release.

**Comment by cldwalker** [comment]
Thanks!
