### ISSUE TITLE
Idea: Config file to let users configure useful default columns in table view

### ISSUE THREAD

**Issue by cldwalker** [metreeca/self#3]
**Is your feature request related to a problem or a specific use case?**

Yes. I'm using self to view 100+ smallish collections modeled primarily with schema.org and my [personal ontology](https://gist.github.com/cldwalker/442b412ba9e1d0fae06772d503b0a298#file-types-md). This means that most of my collections share common fields across all collections e.g. name, description, url, etc. Each time I navigate to any of these collection in table view, I have to populate the same columns in order to see anything useful. It would be nice if I could configure this myself via a config file so I don't have to repetitively, manually configure each new collection type. I'm aware that I can save a report but with the number of collections I have (and more coming), this manual work never ceases.

**Describe the solution you'd like**

I would like to interface with a language-agnostic data format e.g. a JSON file. Since my default columns are pretty repetitive, it would be trivial for me to generate my desired default columns for all of my collections. Ideally a format as simple as the following would suffice:
```
{"Collection Type 1" [{"name": "field1", "type": "integer"}]
 "Collection Type 2" ...}
```

**Describe alternatives you've considered**

I've manually been creating the same columns for each collection type and I don't consider this user friendly. I've also worked off a saved report but this is still taking a lot of effort to update and maintain.  I would consider automating generating a report but the data format is fairly implementation specific with a number of namespaces and bean specific terminology. A simple data format as suggested above would be user friendly and not couple the view implementation to a config format. I also don't know if using a report would result in reasonable load times as I create configs for close to a dozen collections

**Additional thoughts**

If you could point me to where to do this in the code, I may attempt this in my own fork. I'd of course be happy if some version of this landed in self itself.

Cheers

**Comment by knoan** [comment]
Not completely sure about your use case; are the generated reports expected to be:

1. linked from outside metreeca/self;
2. or manually loaded from inside the UI?

**Comment by cldwalker** [comment]
If either option were supported to load a config I would be thrilled. I'm more interested in the functionality and it being performant e.g. it doesn't take 30s to load a config for 100 collections. If I were running self locally it could also be something specified at startup time.

**Comment by knoan** [comment]
We reviewed the whole matter and introducing this feature in a generic way would be a non-trivial effort; in the short term we'd suggest either to:

1. use a single report showing all items in your dataset with a type facet for selecting the relevant subset; 

2. use something like XSLT to automatically transform XML-based simplified report descriptions to fully fledged reports, using a manually assembled report as a starting template.

Concerning solution 1., note that facets with large option collections may be textually filtered to quickly focus on the required items (as shown in the following screenshot)

![large facets](https://user-images.githubusercontent.com/6105462/57061742-52c8fb00-6cbe-11e9-89b4-239be6a61e58.png)

**Comment by cldwalker** [comment]
With the first suggestion, I'd have to manually change columns almost every time I change/filter by a collection type as most collections have columns that differ. Unfortunately that doesn't alleviate much pain. For the second suggestion, I'm open to generating XML reports but I suspect generating a report with a 100+ collections is going to lead to an unusable start time. If I end up trying the second solution, I'll let you know what issues I run into

Any pointers would be appreciated on which class(es) instantiate the columns for a collection type in the table view

**Comment by knoan** [comment]
> With the first suggestion, I'd have to manually change columns almost every time I change/filter by a collection type as most collections have columns that differ. Unfortunately that doesn't alleviate much pain.

Agreed; I incorrectly gathered that all collections shared the same fields.

> For the second suggestion, I'm open to generating XML reports but I suspect generating a report with a 100+ collections is going to lead to an unusable start time.

Right now it's not feasible to generate a single report with all defaults: each collection requires a dedicated xml document. 

The feature you suggested (a JSON based config file for defining defaults for multiple collections) is being evaluated for possible inclusion in a future release, but we aren't currently able to commit to a specific schedule.

> Any pointers would be appreciated on which class(es) instantiate the columns for a collection type in the table view

The attached template provides a starting point for defining your own reports: have a look at the comments; the tricky part will be generating a unique UUID…

[Template.xml.zip](https://github.com/metreeca/self/files/3153590/Template.xml.zip)
